package models

type Employee struct {
	ID                            string               `json:"Id"`
	WorldID                       string               `json:"WorldId"`
	ClassCertifications           []ClassCertification `json:"ClassCertifications"`
	Pseudo                        string               `json:"Pseudo"`
	CompanyID                     string               `json:"CompanyId"`
	FlightHoursTotalBeforeHiring  float64              `json:"FlightHoursTotalBeforeHiring"`
	FlightHoursInCompany          float64              `json:"FlightHoursInCompany"`
	TotalLandings                 int                  `json:"TotalLandings"`
	Weight                        float64              `json:"Weight"`
	BirthDate                     string               `json:"BirthDate"`
	Fatigue                       float64              `json:"Fatigue"`
	Punctuality                   float64              `json:"Punctuality"`
	Comfort                       float64              `json:"Comfort"`
	Happiness                     float64              `json:"Happiness"`
	CurrentAircraftID             string               `json:"CurrentAircraftId,omitempty"`
	CurrentAircraft               EmbeddedAircraft     `json:"CurrentAircraft,omitempty"`
	HomeAirportID                 string               `json:"HomeAirportId"`
	HomeAirport                   EmbeddedAirport      `json:"HomeAirport"`
	PerFlightHourWages            float64              `json:"PerFlightHourWages"`
	WeeklyGuaranteedSalary        float64              `json:"WeeklyGarantedSalary"`
	PerFlightHourSalary           float64              `json:"PerFlightHourSalary"`
	Category                      int                  `json:"Category"`
	Status                        int                  `json:"Status"`
	LastStatusChange              string               `json:"LastStatusChange"`
	FlightDutyStart               string               `json:"FlightDutyStart,omitempty"`
	CurrentTotalFlightHoursInDuty float64              `json:"CurrentTotalFlightHoursInDuty"`
	HiredSince                    string               `json:"HiredSince,omitempty"`
	LastPaymentDate               string               `json:"LastPaymentDate,omitempty"`
	AvatarImageName               string               `json:"AvatarImageName"`
	UnpaidFlightHours             float64              `json:"UnpaidFlightHours"`
	InitialPseudo                 string               `json:"InitialPseudo"`
	IsOnline                      bool                 `json:"IsOnline"`
	FlightDutyEnd                 string               `json:"FlightDutyEnd,omitempty"`
	FlightHoursGrandTotal         float64              `json:"FlightHoursGrandTotal"`
	CurrentAirportID              string               `json:"CurrentAirportId,omitempty"`
	CurrentAirport                CurrentAirport       `json:"CurrentAirport,omitempty"`
	UserID                        string               `json:"UserID,omitempty"`
	BusyUntil                     string               `json:"BusyUntil,omitempty"`
	LastWorkTime                  string               `json:"LastWorkTime,omitempty"`
}

type ClassCertification struct {
	ID              string        `json:"Id"`
	PeopleID        string        `json:"PeopleId"`
	AircraftClassID string        `json:"AircraftClassId"`
	AircraftClass   AircraftClass `json:"AircraftClass"`
	LastValidation  string        `json:"LastValidation"`
	Comments        string        `json:"Comments,omitempty"`
}

type CurrentAirport struct {
	ID                                 string  `json:"Id"`
	ICAO                               string  `json:"ICAO"`
	HasNoRunways                       bool    `json:"HasNoRunways"`
	TimeOffsetInSec                    float64 `json:"TimeOffsetInSec"`
	LocalTimeOpenInHoursSinceMidnight  float64 `json:"LocalTimeOpenInHoursSinceMidnight"`
	LocalTimeCloseInHoursSinceMidnight float64 `json:"LocalTimeCloseInHoursSinceMidnight"`
	IATA                               string  `json:"IATA"`
	Name                               string  `json:"Name"`
	State                              string  `json:"State"`
	CountryCode                        string  `json:"CountryCode"`
	CountryName                        string  `json:"CountryName"`
	City                               string  `json:"City"`
	Latitude                           float64 `json:"Latitude"`
	Longitude                          float64 `json:"Longitude"`
	Elevation                          float64 `json:"Elevation"`
	HasLandRunway                      bool    `json:"HasLandRunway"`
	HasWaterRunway                     bool    `json:"HasWaterRunway"`
	HasHelipad                         bool    `json:"HasHelipad"`
	Size                               int     `json:"Size"`
	TransitionAltitude                 int     `json:"TransitionAltitude"`
	IsNotInVanillaFSX                  bool    `json:"IsNotInVanillaFSX"`
	IsNotInVanillaP3D                  bool    `json:"IsNotInVanillaP3D"`
	IsNotInVanillaXPLANE               bool    `json:"IsNotInVanillaXPLANE"`
	IsNotInVanillaFS2020               bool    `json:"IsNotInVanillaFS2020"`
	IsClosed                           bool    `json:"IsClosed"`
	IsValid                            bool    `json:"IsValid"`
	MagVar                             float64 `json:"MagVar"`
	IsAddon                            bool    `json:"IsAddon"`
	Description                        string  `json:"Description,omitempty"`
	Orientation                        float64 `json:"Orientation"`
	HomeWebSiteUrl                     string  `json:"HomeWebSiteUrl,omitempty"`
	WikiUrl                            string  `json:"WikiUrl"`
	DisplaySceneryInSim                bool    `json:"DisplaySceneryInSim"`
	SceneryLatitude                    float64 `json:"SceneryLatitude"`
	SceneryLongitude                   float64 `json:"SceneryLongitude"`
	RandomSeed                         int     `json:"RandomSeed"`
	LastRandomSeedGeneration           string  `json:"LastRandomSeedGeneration"`
	IsMilitary                         bool    `json:"IsMilitary"`
	HasLights                          bool    `json:"HasLights"`
	IsBasecamp                         bool    `json:"IsBasecamp"`
	LastHangarFeesProcessDate          string  `json:"LastHangarFeesProcessDate"`
	MapSurfaceType                     int     `json:"MapSurfaceType"`
	CreationDate                       string  `json:"CreationDate"`
	IsInSimbrief                       bool    `json:"IsInSimbrief"`
	AirportSource                      int     `json:"AirportSource"`
	LastVeryShortRequestDate           string  `json:"LastVeryShortRequestDate,omitempty"`
	LastSmallTripRequestDate           string  `json:"LastSmallTripRequestDate"`
	LastMediumTripRequestDate          string  `json:"LastMediumTripRequestDate"`
	LastShortHaulRequestDate           string  `json:"LastShortHaulRequestDate"`
	LastMediumHaulRequestDate          string  `json:"LastMediumHaulRequestDate,omitempty"`
	LastLongHaulRequestDate            string  `json:"LastLongHaulRequestDate,omitempty"`
	DisplayName                        string  `json:"DisplayName"`
	UTCTimeOpenInHoursSinceMidnight    float64 `json:"UTCTimeOpenInHoursSinceMidnight"`
	UTCTimeCloseInHoursSinceMidnight   float64 `json:"UTCTimeCloseInHoursSinceMidnight"`
	LastMETARDate                      string  `json:"LastMETARDate,omitempty"`
}
