package models

type Flight struct {
	ID                                         string                `json:"Id"`
	AircraftID                                 string                `json:"AircraftId"`
	Aircraft                                   EmbeddedAircraft      `json:"Aircraft"`
	CompanyID                                  string                `json:"CompanyId"`
	Company                                    Company               `json:"Company"`
	DepartureAirportID                         string                `json:"DepartureAirportId"`
	DepartureAirport                           EmbeddedAirport       `json:"DepartureAirport"`
	ArrivalIntendedAirportID                   string                `json:"ArrivalIntendedAirportId"`
	ArrivalIntendedAirport                     EmbeddedAirport       `json:"ArrivalIntendedAirport"`
	ArrivalAlternateAirportID                  string                `json:"ArrivalAlternateAirportId"`
	Registered                                 bool                  `json:"Registered"`
	Category                                   int                   `json:"Category"`
	StartTime                                  string                `json:"StartTime"`
	EngineOnTime                               string                `json:"EngineOnTime"`
	AirborneTime                               string                `json:"AirborneTime"`
	IntendedFlightLevel                        int                   `json:"IntendedFlightLevel"`
	Passengers                                 int                   `json:"Passengers"`
	Cargo                                      int                   `json:"Cargo"`
	AddedFuelQty                               int                   `json:"AddedFuelQty"`
	IsAI                                       bool                  `json:"IsAI"`
	VerticalSpeedAtTouchdownMpS                float64               `json:"VerticalSpeedAtTouchdownMpS"`
	MaxGForce                                  float64               `json:"MaxGForce"`
	MinGForce                                  float64               `json:"MinGForce"`
	MaxBank                                    float64               `json:"MaxBank"`
	MaxPitch                                   float64               `json:"MaxPitch"`
	HasStalled                                 bool                  `json:"HasStalled"`
	HasOverspeeded                             bool                  `json:"HasOverspeeded"`
	Engine1Status                              int                   `json:"Engine1Status"`
	Engine2Status                              int                   `json:"Engine2Status"`
	Engine3Status                              int                   `json:"Engine3Status"`
	Engine4Status                              int                   `json:"Engine4Status"`
	Engine5Status                              int                   `json:"Engine5Status"`
	Engine6Status                              int                   `json:"Engine6Status"`
	FlightCrews                                []FlightCrewMember    `json:"FlightCrews"`
	XPFlight                                   int                   `json:"XPFlight"`
	XPFlightBonus                              float64               `json:"XPFlightBonus"`
	XPMissions                                 int                   `json:"XPMissions"`
	CargosTotalWeight                          float64               `json:"CargosTotalWeight"`
	PAXCount                                   int                   `json:"PAXCount"`
	AircraftCurrentFOB                         float64               `json:"AircraftCurrentFOB"`
	AircraftCurrentAltitude                    float64               `json:"AircraftCurrentAltitude"`
	ActualCruiseAltitude                       float64               `json:"ActualCruiseAltitude"`
	ActualConsumptionAtCruiseLevelInLbsPerHour float64               `json:"ActualConsumptionAtCruiseLevelInLbsPerHour"`
	ActualTotalFuelConsumptionInLbs            float64               `json:"ActualTotalFuelConsumptionInLbs"`
	ActualConsumptionAtCruiseLevelInGalPerHour float64               `json:"ActualConsumptionAtCruiseLevelInGalPerHour"`
	ActualTASAtCruiseLevel                     float64               `json:"ActualTASAtCruiseLevel"`
	ActualCruiseTimeInMinutes                  float64               `json:"ActualCruiseTimeInMinutes"`
	ActualPressureAltitude                     float64               `json:"ActualPressureAltitude"`
	RegisterState                              int                   `json:"RegisterState"`
	WrongFuelDetected                          bool                  `json:"WrongFuelDetected"`
	WrongWeightDetected                        bool                  `json:"WrongWeightDetected"`
	TimeOffset                                 float64               `json:"TimeOffset"`
	StartLatitude                              float64               `json:"StartLatitude"`
	StartLongitude                             float64               `json:"StartLongitude"`
	StartHeading                               float64               `json:"StartHeading"`
	UseFreelanceRouteSchedule                  bool                  `json:"UseFreelanceRouteSchedule"`
	RestCrewAfterWarp                          bool                  `json:"RestCrewAfterWarp"`
	CanResumeOrAbort                           bool                  `json:"CanResumeOrAbort"`
	EngineOnRealTime                           string                `json:"EngineOnRealTime"`
	AirborneRealTime                           string                `json:"AirborneRealTime"`
	AircraftAddonID                            string                `json:"AircraftAddonId,omitempty"`
	AircraftAddon                              EmbeddedAircraftAddon `json:"AircraftAddon,omitempty"`
	ArrivalActualAirportID                     string                `json:"ArrivalActualAirportId,omitempty"`
	ArrivalActualAirport                       EmbeddedAirport       `json:"ArrivalActualAirport,omitempty"`
	ResultComments                             string                `json:"ResultComments,omitempty"`
	EndTime                                    string                `json:"EndTime,omitempty"`
	EngineOffTime                              string                `json:"EngineOffTime,omitempty"`
	LandedTime                                 string                `json:"LandedTime,omitempty"`
	Score                                      float64               `json:"Score,omitempty"`
	EngineOffRealTime                          string                `json:"EngineOffRealTime,omitempty"`
	LandedRealTime                             string                `json:"LandedRealTime,omitempty"`
}

type FlightCrewMember struct {
	ID       string `json:"Id"`
	FlightID string `json:"FlightId"`
	PersonID string `json:"PeopleId"`
	Role     int    `json:"Role"`
	Person   Person `json:"People"`
}

type Person struct {
	ID                            string               `json:"Id"`
	WorldID                       string               `json:"WorldId"`
	ClassCertifications           []ClassCertification `json:"ClassCertifications"`
	Pseudo                        string               `json:"Pseudo"`
	CompanyID                     string               `json:"CompanyId"`
	Company                       Company              `json:"Company,omitempty"`
	FlightHoursTotalBeforeHiring  float64              `json:"FlightHoursTotalBeforeHiring"`
	FlightHoursInCompany          float64              `json:"FlightHoursInCompany"`
	TotalLandings                 int                  `json:"TotalLandings"`
	Weight                        float64              `json:"Weight"`
	BirthDate                     string               `json:"BirthDate"`
	Fatigue                       float64              `json:"Fatigue"`
	Punctuality                   float64              `json:"Punctuality"`
	Comfort                       float64              `json:"Comfort"`
	Happiness                     float64              `json:"Happiness"`
	CurrentAircraftID             string               `json:"CurrentAircraftId,omitempty"`
	CurrentAircraft               EmbeddedAircraft     `json:"CurrentAircraft,omitempty"`
	HomeAirportID                 string               `json:"HomeAirportId"`
	HomeAirport                   EmbeddedAirport      `json:"HomeAirport,omitempty"`
	PerFlightHourWages            float64              `json:"PerFlightHourWages"`
	WeeklyGarantedSalary          float64              `json:"WeeklyGarantedSalary"`
	PerFlightHourSalary           float64              `json:"PerFlightHourSalary"`
	Category                      int                  `json:"Category"`
	Status                        int                  `json:"Status"`
	LastStatusChange              string               `json:"LastStatusChange"`
	FlightDutyStart               string               `json:"FlightDutyStart,omitempty"`
	CurrentTotalFlightHoursInDuty float64              `json:"CurrentTotalFlightHoursInDuty"`
	HiredSince                    string               `json:"HiredSince,omitempty"`
	LastPaymentDate               string               `json:"LastPaymentDate,omitempty"`
	AvatarImageName               string               `json:"AvatarImageName"`
	UnpaidFlightHours             float64              `json:"UnpaidFlightHours"`
	InitialPseudo                 string               `json:"InitialPseudo"`
	IsOnline                      bool                 `json:"IsOnline"`
	FlightDutyEnd                 string               `json:"FlightDutyEnd,omitempty"`
	FlightHoursGrandTotal         float64              `json:"FlightHoursGrandTotal"`
	AvatarUrl                     string               `json:"AvatarUrl"`
	UserID                        string               `json:"UserID,omitempty"`
	CurrentAirportID              string               `json:"CurrentAirportId,omitempty"`
	CurrentAirport                EmbeddedAirport      `json:"CurrentAirport,omitempty"`
}
