package models

type VAMember struct {
	ID        string `json:"Id"`
	VAId      string `json:"VAId"`
	CompanyID string `json:"CompanyId"`
	Company   struct {
		ID                                 string  `json:"Id"`
		WorldID                            string  `json:"WorldId"`
		Name                               string  `json:"Name"`
		AirlineCode                        string  `json:"AirlineCode"`
		LastConnection                     string  `json:"LastConnection"`
		LastReportDate                     string  `json:"LastReportDate"`
		Reputation                         float64 `json:"Reputation"`
		CreationDate                       string  `json:"CreationDate"`
		DifficultyLevel                    int     `json:"DifficultyLevel"`
		UTCOffsetinHours                   float64 `json:"UTCOffsetinHours"`
		Paused                             bool    `json:"Paused"`
		Level                              int     `json:"Level"`
		LevelXP                            int     `json:"LevelXP"`
		TransportEmployeeInstant           bool    `json:"TransportEmployeeInstant"`
		TransportPlayerInstant             bool    `json:"TransportPlayerInstant"`
		ForceTimeInSimulator               bool    `json:"ForceTimeInSimulator"`
		UseSmallAirports                   bool    `json:"UseSmallAirports"`
		UseOnlyVanillaAirports             bool    `json:"UseOnlyVanillaAirports"`
		EnableSkillTree                    bool    `json:"EnableSkillTree"`
		CheckrideLevel                     int     `json:"CheckrideLevel"`
		EnableLandingPenalities            bool    `json:"EnableLandingPenalities"`
		EnableEmployeesFlightDutyAndSleep  bool    `json:"EnableEmployeesFlightDutyAndSleep"`
		AircraftRentLevel                  int     `json:"AircraftRentLevel"`
		EnableCargosAndChartersLoadingTime bool    `json:"EnableCargosAndChartersLoadingTime"`
		InSurvival                         bool    `json:"InSurvival"`
		PayBonusFactor                     float64 `json:"PayBonusFactor"`
		EnableSimFailures                  bool    `json:"EnableSimFailures"`
		DisableSeatsConfigCheck            bool    `json:"DisableSeatsConfigCheck"`
		RealisticSimProcedures             bool    `json:"RealisticSimProcedures"`
		TravelTokens                       int     `json:"TravelTokens"`
		LastWeeklyManagementsPaymentDate   string  `json:"LastWeeklyManagementsPaymentDate"`
		SkillTreeResetCount                int     `json:"SkillTreeResetCount"`
		IndustryPoints                     int     `json:"IndustryPoints"`
		TotalIndustryPoints                int     `json:"TotalIndustryPoints"`
		TotalContractsCompleted            int     `json:"TotalContractsCompleted"`
		TotalContractsEarnedCredits        float64 `json:"TotalContractsEarnedCredits"`
		CompanyType                        int     `json:"CompanyType"`
		AutoUnloadMerchandises             bool    `json:"AutoUnloadMerchandises"`
		ExcludeAirportsNotInSimbrief       bool    `json:"ExcludeAirportsNotInSimbrief"`
		DisableFlightScoring               bool    `json:"DisableFlightScoring"`
		EnableFlightScoringLights          bool    `json:"EnableFlightScoringLights"`
		ManagementMode                     int     `json:"ManagementMode"`
		IsAdvancedManagementModeUnlocked   bool    `json:"IsAdvancedManagementModeUnlocked"`
		MainAircraftID                     string  `json:"MainAircraftId,omitempty"`
		LastSwapDate                       string  `json:"LastSwapDate,omitempty"`
		Callsign                           string  `json:"Callsign,omitempty"`
		PausedDate                         string  `json:"PausedDate,omitempty"`
		CurrentBadgeID                     string  `json:"CurrentBadgeId,omitempty"`
		CurrentBadgeUrl                    string  `json:"CurrentBadgeUrl,omitempty"`
		CurrentBadgeName                   string  `json:"CurrentBadgeName,omitempty"`
		SayIntentionsPilotKey              string  `json:"SayIntentionsPilotKey,omitempty"`
		LastManagementModeUpdateDate       string  `json:"LastManagementModeUpdateDate,omitempty"`
	} `json:"Company"`
	Aircrafts []struct {
		ID         string `json:"Id"`
		VAMemberID string `json:"VAMemberId"`
		AircraftID string `json:"AircraftId"`
	} `json:"Aircrafts"`
	Peoples []struct {
		ID         string `json:"Id"`
		VAMemberID string `json:"VAMemberId"`
		EmployeeID string `json:"EmployeeId"`
	} `json:"Peoples"`
	VARoleID string `json:"VARoleId"`
	VARole   struct {
		ID                                     string  `json:"Id"`
		VAId                                   string  `json:"VAId"`
		Name                                   string  `json:"Name"`
		Permission                             int     `json:"Permission"`
		IsDefaultNewRole                       bool    `json:"IsDefaultNewRole"`
		Color                                  string  `json:"Color"`
		PayPercent                             float64 `json:"PayPercent"`
		IsHidden                               bool    `json:"IsHidden"`
		RestrictLoadingVAJobsIntoNonVAAircraft bool    `json:"RestrictLoadingVAJobsIntoNonVAAircraft"`
		RestrictLoadingNonVAJobsIntoVAAircraft bool    `json:"RestrictLoadingNonVAJobsIntoVAAircraft"`
		PayWeekly                              float64 `json:"PayWeekly"`
		PayPerFlightHour                       float64 `json:"PayPerFlightHour"`
	} `json:"VARole"`
	TotalCargosTransportedLbs float64 `json:"TotalCargosTransportedLbs"`
	TotalPAXsTransported      int     `json:"TotalPAXsTransported"`
	TotalEarnedCredits        float64 `json:"TotalEarnedCredits"`
	TotalSpentCredits         float64 `json:"TotalSpentCredits"`
	NumberOfFlights           int     `json:"NumberOfFlights"`
	FlightHours               float64 `json:"FlightHours"`
	Color                     string  `json:"Color"`
	AcceptMigration           bool    `json:"AcceptMigration"`
	ReputationImpact          float64 `json:"ReputationImpact"`
	LastVAFlightDate          string  `json:"LastVAFlightDate,omitempty"`
	LastWeeklyPay             string  `json:"LastWeeklyPay,omitempty"`
}
